name: Reload web app on PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Reload web app on PythonAnywhere
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_API_KEY: ${{ secrets.PA_API_KEY }}
        run: |
          curl -s -X POST -H "Authorization: Token $PA_API_KEY" \
            "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/${PA_USERNAME}.pythonanywhere.com/reload/"
